### ISSUE TITLE
Use a Factory class to build User object instead of directly creating it in the Signup interactor

### ISSUE THREAD

**Issue by Pranjal-R-Agrawal** [Pranjal-R-Agrawal/CSC207_Course_Project_141#10]
The interaction must have only 3 functions - collect input data from controller, process it with the help of the DAO and entity creations and send the output data to the presenter. The Week5ca assignment follows the same strategy.

**Comment by SidharthSawhney** [comment]
I see a general design problem we haven't addressed till now for the entities.

We must have a ConcreteUser class which implements User interface and ConcreteUserFactory class which implements the UserFactory interface. So we must creat 2 interface and 2 concrete implementation (one for each). This will help with Dependency Inversion. Thank you!
