### ISSUE TITLE
A class for creating new windows

### ISSUE THREAD

**Issue by Pranjal-R-Agrawal** [Pranjal-R-Agrawal/CSC207_Course_Project_141#28]
Currently, there are two places other than `Main` where a new window is created, 

- `PostAndCommentsView`, where the `createComment` view and a window are created
- `ViewManager`, where a window is created for `PostAndCommentsView`

A new class should be created for creating windows and should be injected where necessary.

**Comment by YathusanK** [comment]
Got merged into main
