### ISSUE TITLE
Builder Design Pattern for MongoDBDAO

### ISSUE THREAD

**Issue by SidharthSawhney** [Pranjal-R-Agrawal/CSC207_Course_Project_141#4]
There seem to be a lot of parameterized and default constructors that depend on each other to create the DAO. How about we use the builder design pattern which will allow us to optionally configure as many parameters as we want before we build the DAO. 

Read this:
https://medium.com/javarevisited/design-patterns-101-factory-vs-builder-vs-fluent-builder-da2babf42113
https://github.com/CSC207-UofT/design-pattern-samples/tree/main/src/builder/with_builder

Lets discuss on how we can go about implementing this idea.

**Comment by Pranjal-R-Agrawal** [comment]
Implemented in commit - https://github.com/Pranjal-R-Agrawal/CSC207_Course_Project_141/commit/33a2f9996fda594061ca1f99693a16a42bccf55c
