### ISSUE TITLE
Better input validation for signing up and logging in

### ISSUE THREAD

**Issue by Pranjal-R-Agrawal** [Pranjal-R-Agrawal/CSC207_Course_Project_141#6]
Currently the input validation for signing up is broken in that an empty string is not accepted but a string containing spaces is accepted (though stored as an empty string in the database). Further, there is no way to input an empty string when logging in.

Similar fixes need to be made elsewhere throughout the signup and logging use cases for handling the inputs.

Further, the string passed to the database should be the exact same as the one entered; incorrect inputs should be rejected instead of being modified without the user being informed.

**Comment by SidharthSawhney** [comment]
https://github.com/paulgries/LoginCleanArchitecture/tree/main/src/entity

This link to the LoginCleanArchitecture under "entity" shows that the validation is considered an entity. An interface and a concrete implementation is made for every validation. We could try to do the same to follow the pattern, but i do not understand why should we consider a validation check an entity?

**Comment by Pranjal-R-Agrawal** [comment]
I agree, we could follow the same pattern.

I am not sure either why it's considered an entity. Perhaps it's because they didn't want to create a dedicated folder for a single validator?

We could get it clarified next lecture.
